### PR TITLE
Remove unnecessary stuff from WindowsStore project files

### PR DESCRIPTION
**Pull request by szilvaa**
Neither AppxPackageArtifactsDir nor ProjectPriFullPath are necessary. Their defaults work correctly in VS 2015 RTM.
In fact, if you specify ProjectPriFullPath then "Deploy" from VS does not work because it cannot find resource.pri. 
Then, if you remove ProjectPriFullPath, the 'try compile' phase of CMake falls apart because it tries to generate the resource.pri in a directory that does not exist. Removing AppxPackageArtifactsDir fixes this problem.

FWIW, neither of these properties are specified in vcxproj files generated by visual studio.

### CODE REVIEW

**Comment by khouzam** [comment]
Hi @szilvaa 

This is causing issues because you don't have a manifest specified for your application and the other required files to build a proper Appx. This code is really only there for the Try/Compile stage which doesn't have an app manifest or resources.

**Comment by szilvaa** [comment]
Are you talking about .appXManifest or some other manifest. Cmake generates package.appXmanifest file. When I remove both of these properties then both TryCompile and regular build are happy.

**Comment by khouzam** [comment]
Yes, I'm talking about the .appxManifest. CMake will generate an appx Manifest file, which is generic and is only there for the try/compile step. You should be setting the proper appx manifest file for your application as well as the certificate and icons and splashscreen.

**Comment by szilvaa** [comment]
Ok. I think I see what you mean but I still don't understand why you need to have these 2 properties. Here's what I have:
1. For (cross platform) unit test exes I don't want to manually create any manifest and assets. The generated manifest and assets work fine.
2. For the actual UWP app (which incorporates cross platform components) I create an manifest and assets and point cmake to them.  This also works. (simply copied the assets from a VS generated project, the only change I had to make to the manifest is to remove "Assets\" prefix from the png files. 

Clearly, there's some pattern of usage that these properties intend to facilitate but I don't quite get what this pattern is. They definitely break #1 above and they don't seem to be necessary for #2 either.

Can you provide some guidance on how Cmake projects are supposed to be laid out when targeting WindowsStore? Do you have some samples somewhere?

Thanks,
Albert

**Comment by szilvaa** [comment]
One more bit of info: I can use the "Assets\" prefixes in the manifest with Cmake. I just need to set the VS_DEPLOYMENT_LOCATION property on the png files, like this:

set_property(SOURCE ${ASSET_FILES} PROPERTY VS_DEPLOYMENT_LOCATION "Assets")

**Comment by bobbrow** [comment]
We're sorry that this PR was not accepted and left open for so long.  If you would still like to move forward with this PR, we recommend you submit a merge request into the upstream "official" Kitware repository: https://gitlab.kitware.com/cmake/cmake/-/merge_requests

**Pull request closed without merging**
